import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, expect, it } from "vitest";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entrypoint = join(root, "dist/cli/main.js");
const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((path) => rm(path, { recursive: true })));
});

it("builds an arbitrary bundle and fails closed on invalid Typst", async () => {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "doc-gen-"));
  temporaryDirectories.push(temporaryDirectory);
  const output = join(temporaryDirectory, "output");
  const callerFile = join(output, "keep.txt");
  await mkdir(output);
  await writeFile(callerFile, "caller-owned\n", "utf8");

  const success = run(join(root, "test/fixtures/valid/typst.json"), output);
  expect(success.status).toBe(0);
  expect(success.stderr).toBe("");
  const result = JSON.parse(success.stdout) as {
    readonly ok: boolean;
    readonly targetUnitId: string;
    readonly diagnostics: readonly { readonly severity?: string }[];
    readonly artifacts: {
      readonly program: string;
      readonly diagnostics: string;
      readonly document: string;
      readonly typstPreviews: readonly string[];
      readonly univerScreenshots: readonly string[];
    };
    readonly visualReviewRequired: boolean;
  };
  expect(result).toMatchObject({
    ok: true,
    targetUnitId: "univer-cli-sdk-release-brief",
    visualReviewRequired: true,
  });
  expect(result.diagnostics.some((diagnostic) => diagnostic.severity === "error")).toBe(false);
  expect(await readFile(result.artifacts.program, "utf8")).toContain(
    "Generated by @univer-cli/doc-typst-facade",
  );
  expect(JSON.parse(await readFile(result.artifacts.diagnostics, "utf8"))).toMatchObject({
    schemaVersion: 1,
  });

  const document = JSON.parse(await readFile(result.artifacts.document, "utf8")) as {
    readonly id: string;
    readonly title: string;
    readonly body?: {
      readonly dataStream?: string;
      readonly tables?: readonly unknown[];
    };
  };
  expect(document).toMatchObject({
    id: "univer-cli-sdk-release-brief",
    title: "Univer CLI SDK 发布简报",
  });
  expect(document.body?.dataStream).toContain("核心能力");
  expect(document.body?.dataStream).toContain("下一步");
  expect(document.body?.tables).toHaveLength(1);
  for (const path of [...result.artifacts.typstPreviews, ...result.artifacts.univerScreenshots]) {
    expect((await readFile(path)).subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
  }
  expect(await readFile(callerFile, "utf8")).toBe("caller-owned\n");

  const failureRun = run(join(root, "test/fixtures/invalid"), output);
  expect(failureRun.status).toBe(1);
  expect(failureRun.stdout).toBe("");
  const failure = JSON.parse(failureRun.stderr) as {
    readonly ok: boolean;
    readonly code: string;
    readonly diagnostics: readonly { readonly severity?: string }[];
    readonly artifacts: Record<string, unknown>;
  };
  expect(failure).toMatchObject({ ok: false, code: "COMPILE_ERROR" });
  expect(failure.diagnostics.some((diagnostic) => diagnostic.severity === "error")).toBe(true);
  expect(failure.artifacts).not.toHaveProperty("program");
  expect(failure.artifacts).not.toHaveProperty("document");
  expect(failure.artifacts).not.toHaveProperty("univerScreenshots");
  await expect(readFile(join(output, "document.js"))).rejects.toMatchObject({ code: "ENOENT" });
  await expect(readFile(join(output, "document.json"))).rejects.toMatchObject({ code: "ENOENT" });
  expect(await readFile(callerFile, "utf8")).toBe("caller-owned\n");
}, 60_000);

function run(bundle: string, output: string) {
  return spawnSync(
    process.execPath,
    [entrypoint, "compile-typst", bundle, "--out", output, "--json"],
    {
      encoding: "utf8",
      env: { ...process.env, UNIVER_LICENSE: process.env["UNIVER_LICENSE"] ?? "" },
      timeout: 45_000,
    },
  );
}
