import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, expect, it } from "vitest";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const entrypoint = join(root, "dist/cli/main.js");
const temporaryDirectories: string[] = [];

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map((path) => rm(path, { recursive: true })));
});

it("builds an arbitrary bundle and fails closed on invalid Typst", async () => {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "doc-gen-"));
  temporaryDirectories.push(temporaryDirectory);
  const output = join(temporaryDirectory, "output");
  const callerFile = join(output, "keep.txt");
  await mkdir(output);
  await writeFile(callerFile, "caller-owned\n", "utf8");

  const success = run([
    "compile-typst",
    join(root, "test/fixtures/valid/typst.json"),
    "--out",
    output,
    "--json",
  ]);
  expect(success.status).toBe(0);
  expect(success.stderr).toBe("");
  const result = JSON.parse(success.stdout) as {
    readonly ok: boolean;
    readonly targetUnitId: string;
    readonly diagnostics: readonly { readonly severity?: string }[];
    readonly artifacts: {
      readonly program: string;
      readonly diagnostics: string;
      readonly document: string;
      readonly typstPreviews: readonly string[];
      readonly univerScreenshots: readonly string[];
    };
    readonly visualReviewRequired: boolean;
  };
  expect(result).toMatchObject({
    ok: true,
    targetUnitId: "univer-cli-sdk-release-brief",
    visualReviewRequired: true,
  });
  expect(result.diagnostics.some((diagnostic) => diagnostic.severity === "error")).toBe(false);
  expect(await readFile(result.artifacts.program, "utf8")).toContain(
    "Generated by @univer-cli/doc-typst-facade",
  );
  expect(JSON.parse(await readFile(result.artifacts.diagnostics, "utf8"))).toMatchObject({
    schemaVersion: 1,
  });

  const document = JSON.parse(await readFile(result.artifacts.document, "utf8")) as {
    readonly id: string;
    readonly title: string;
    readonly body?: {
      readonly dataStream?: string;
      readonly tables?: readonly unknown[];
    };
  };
  expect(document).toMatchObject({
    id: "univer-cli-sdk-release-brief",
    title: "Univer CLI SDK 发布简报",
  });
  expect(document.body?.dataStream).toContain("核心能力");
  expect(document.body?.dataStream).toContain("下一步");
  expect(document.body?.tables).toHaveLength(1);
  for (const path of [...result.artifacts.typstPreviews, ...result.artifacts.univerScreenshots]) {
    expect((await readFile(path)).subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
  }
  expect(await readFile(callerFile, "utf8")).toBe("caller-owned\n");

  const failureRun = run([
    "compile-typst",
    join(root, "test/fixtures/invalid"),
    "--out",
    output,
    "--json",
  ]);
  expect(failureRun.status).toBe(1);
  expect(failureRun.stdout).toBe("");
  const failure = JSON.parse(failureRun.stderr) as {
    readonly ok: boolean;
    readonly code: string;
    readonly diagnostics: readonly { readonly severity?: string }[];
    readonly artifacts: Record<string, unknown>;
  };
  expect(failure).toMatchObject({ ok: false, code: "COMPILE_ERROR" });
  expect(failure.diagnostics.some((diagnostic) => diagnostic.severity === "error")).toBe(true);
  expect(failure.artifacts).not.toHaveProperty("program");
  expect(failure.artifacts).not.toHaveProperty("document");
  expect(failure.artifacts).not.toHaveProperty("univerScreenshots");
  await expect(readFile(join(output, "document.js"))).rejects.toMatchObject({ code: "ENOENT" });
  await expect(readFile(join(output, "document.json"))).rejects.toMatchObject({ code: "ENOENT" });
  expect(await readFile(callerFile, "utf8")).toBe("caller-owned\n");
}, 60_000);

it("queries APIs, refines a local Doc, and refreshes its screenshot", async () => {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "doc-gen-loop-"));
  temporaryDirectories.push(temporaryDirectory);
  const output = join(temporaryDirectory, "build");
  const compiled = run([
    "compile-typst",
    join(root, "test/fixtures/valid/typst.json"),
    "--out",
    output,
    "--json",
  ]);
  expect(compiled.status).toBe(0);
  const documentPath = join(output, "document.json");

  const found = run(["api", "find", "paragraph", "--unit", "doc"]);
  expect(found.status).toBe(0);
  expect(found.stdout).toContain("FDocument.getParagraphs");
  const shown = run(["api", "show", "FDocumentParagraph.setText"]);
  expect(shown.status).toBe(0);
  expect(shown.stdout).toContain("setText");
  const missing = run(["api", "show", "DefinitelyMissingSymbol"]);
  expect(missing.status).toBe(1);
  expect(missing.stderr).toContain("Unknown symbol");

  const script = join(temporaryDirectory, "refine.js");
  await writeFile(
    script,
    [
      "const paragraph = doc.getParagraphs()[0];",
      'if (!paragraph) throw new Error("paragraph missing");',
      "const changed = paragraph.setText(`${paragraph.getText()} [refined]`);",
      'if (!changed) throw new Error("paragraph update failed");',
      "return { text: paragraph.getText() };",
    ].join("\n"),
  );
  const missingScript = run(["execute", documentPath, "--json"]);
  expect(missingScript.status).toBe(1);
  expect(missingScript.stdout).toBe("");
  expect(JSON.parse(missingScript.stderr)).toMatchObject({
    ok: false,
    code: "ARGUMENT_ERROR",
  });
  const unreadableScript = run([
    "execute",
    documentPath,
    "--file",
    join(temporaryDirectory, "missing.js"),
    "--json",
  ]);
  expect(JSON.parse(unreadableScript.stderr)).toMatchObject({ ok: false, code: "IO_ERROR" });
  const executed = run(["execute", documentPath, "--file", script, "--json"]);
  expect(executed.status).toBe(0);
  expect(executed.stderr).toBe("");
  expect(JSON.parse(executed.stdout)).toMatchObject({
    ok: true,
    targetUnitId: "univer-cli-sdk-release-brief",
    document: documentPath,
    value: { text: expect.stringContaining("[refined]") },
  });
  expect(await readFile(documentPath, "utf8")).toContain("[refined]");

  const beforeFailure = await readFile(documentPath, "utf8");
  const failureScript = join(temporaryDirectory, "fail.js");
  await writeFile(failureScript, 'throw new Error("expected failure");\n');
  const failed = run(["execute", documentPath, "--file", failureScript, "--json"]);
  expect(failed.status).toBe(1);
  expect(failed.stdout).toBe("");
  expect(JSON.parse(failed.stderr)).toMatchObject({ ok: false, code: "EXECUTE_ERROR" });
  expect(await readFile(documentPath, "utf8")).toBe(beforeFailure);

  const invalidReturn = join(temporaryDirectory, "invalid-return.js");
  await writeFile(
    invalidReturn,
    'doc.getParagraphs()[0].setText("must not persist"); return 1n;\n',
  );
  const invalid = run(["execute", documentPath, "--file", invalidReturn, "--json"]);
  expect(invalid.status).toBe(1);
  expect(JSON.parse(invalid.stderr)).toMatchObject({ ok: false, code: "EXECUTE_ERROR" });
  expect(await readFile(documentPath, "utf8")).toBe(beforeFailure);

  const malformed = join(temporaryDirectory, "malformed.json");
  await writeFile(malformed, "{\n");
  const malformedResult = run(["execute", malformed, "--file", script, "--json"]);
  expect(JSON.parse(malformedResult.stderr)).toMatchObject({
    ok: false,
    code: "ARGUMENT_ERROR",
  });
  const missingId = join(temporaryDirectory, "missing-id.json");
  await writeFile(missingId, "{}\n");
  const missingIdResult = run(["execute", missingId, "--file", script, "--json"]);
  expect(JSON.parse(missingIdResult.stderr)).toMatchObject({
    ok: false,
    code: "ARGUMENT_ERROR",
  });

  const screenshots = join(temporaryDirectory, "screenshots");
  const nested = join(screenshots, "nested");
  await mkdir(nested, { recursive: true });
  await writeFile(join(screenshots, "old.png"), "old");
  await writeFile(join(screenshots, "keep.txt"), "keep\n");
  await writeFile(join(nested, "keep.png"), "nested\n");
  const captured = run(["screenshot", documentPath, "--out", screenshots, "--json"]);
  expect(captured.status).toBe(0);
  expect(captured.stderr).toBe("");
  const screenshotResult = JSON.parse(captured.stdout) as {
    readonly screenshots: readonly string[];
  };
  expect(screenshotResult.screenshots.length).toBeGreaterThan(0);
  for (const path of screenshotResult.screenshots) {
    expect((await readFile(path)).subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
  }
  await expect(readFile(join(screenshots, "old.png"))).rejects.toMatchObject({ code: "ENOENT" });
  expect(await readFile(join(screenshots, "keep.txt"), "utf8")).toBe("keep\n");
  expect(await readFile(join(nested, "keep.png"), "utf8")).toBe("nested\n");

  const missingOut = run(["screenshot", documentPath, "--json"]);
  expect(missingOut.status).toBe(1);
  expect(missingOut.stdout).toBe("");
  expect(JSON.parse(missingOut.stderr)).toMatchObject({ ok: false, code: "ARGUMENT_ERROR" });
}, 120_000);

function run(args: readonly string[]) {
  return spawnSync(process.execPath, [entrypoint, ...args], {
    encoding: "utf8",
    env: { ...process.env, UNIVER_LICENSE: process.env["UNIVER_LICENSE"] ?? "" },
    timeout: 45_000,
  });
}
